common:
  api_name: library_example
  api_version: v1
  organization_name: google-cloud
  src_proto_paths:
  - ${GOOGLEAPIS}/google/example/library/v1
  proto_deps:
  - name: google-common-protos
  - name: google-iam-v1
  service_yaml: ${GOOGLEAPIS}/google/example/library/library_example.yaml
  gapic_yaml: ${GOOGLEAPIS}/google/example/library/v1/library_example_gapic.yaml
artifacts:
- name: java_gapic_library
  type: GAPIC
  language: JAVA
  publish_targets:
  - name: google-cloud-java
    location: git@github.com:GoogleCloudPlatform/google-cloud-java.git
    type: GITHUB
    directory_mappings:
    - dest: google-cloud-library-example
  - name: staging-github
    location: git@github.com:googleapis/api-client-staging.git
    type: GITHUB
    directory_mappings:
    - src: java/google-cloud-library-example
      dest: generated/java/gapic-google-cloud-library-example-v1
    - src: java/grpc-google-cloud-library-example-v1
      dest: generated/java/grpc-google-cloud-library-example-v1
    - src: java/proto-google-cloud-library-example-v1
      dest: generated/java/proto-google-cloud-library-example-v1
- name: python_gapic_only_library
  type: GAPIC_ONLY
  language: PYTHON
  publish_targets:
  - name: staging-github
    type: GITHUB
    location: git@github.com:googleapis/api-client-staging.git
    directory_mappings:
    - src: gapic-google-cloud-library-example-v1
      dest: generated/python/gapic-google-cloud-library-example-v1
