---
version: 2.0
jobs:
  build_and_push_docker_image:
    working_directory: /usr/src/artman
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - &checkout_artman
        checkout:
          path: /usr/src/artman/
      - setup_remote_docker
      - run:
          name: Fingers crossed!
          command: |
            echo "Fingers crossed!"
      - restore_cache:
          keys:
            - artman-{{ .Branch }}
          paths:
            - /caches/artman.tar
      - run:
          name: Load Artman Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/artman.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=artman -t artman --build-arg install_artman_from_source=true .
      - run:
          name: Save Artman Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/artman.tar artman
      - save_cache:
          key: artman-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/artman.tar
      - run:
          name: Run golden tests
          command: |
            docker run -it -e RUNNING_IN_ARTMAN_DOCKER=True -v /tmp/reports:/tmp/reports artman /bin/bash -c "pip install pytest; git clone https://github.com/googleapis/googleapis /artman/test/golden/googleapis; py.test -vv /artman/test/golden/artman_golden_test.py --googleapis-dir=/artman/test/golden/googleapis"
      # When build performance is a concern, consider separating this job into
      # a workflow with multiple jobs and have the smoketest run in parallel
      # with additional paid containers.
      - run:
          name: Run smoketests
          command: |
            docker run -it -e RUNNING_IN_ARTMAN_DOCKER=True --name smoketest artman /bin/bash -c "git clone https://github.com/googleapis/googleapis /tmp/googleapis_smoketest; python3 /artman/test/smoketest_artman.py --root-dir=/tmp/googleapis_smoketest --log=/tmp/smoketest.log" || OUT=$?
            docker cp smoketest:/tmp/smoketest.log /tmp/smoketest.log
            if [ $OUT -ne 0 ];then
              exit $OUT
            fi
      - deploy:
          name: Push Artman Docker image
          command: |
            if [ "${DOCKER_EMAIL}" == 'googleapis-publisher@google.com' ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker tag artman "googleapis/artman:AUTO_BUILD_$CIRCLE_BUILD_NUM"
              docker push "googleapis/artman:AUTO_BUILD_$CIRCLE_BUILD_NUM"
              docker tag artman "googleapis/artman:latest"
              docker push "googleapis/artman:latest"
            else
              echo "Environment variables DOCKER_EMAIL, DOCKER_USER, DOCKER_PASS are not properly set in CircleCI project."
              echo "Skip the Artman Docker image publishing step."
            fi
      - run:
          name: Hooray!
          command: echo "Hooray!"
      - store_artifacts:
          path: /artman/test/golden/actual_library_example.golden
      - store_artifacts:
          path: /tmp/smoketest.log

  docs:
    docker:
      - image: python:3.6
    steps:
      - *checkout_artman
      - run:
          name: Install nox.
          command: pip install --upgrade nox-automation
      - run:
          name: Build the docs.
          command: nox -e docs
    working_directory: /usr/src/artman/

  unit-python2.7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox-automation codecov
      - run:
          name: Run unit tests.
          command: nox -e "unit_tests(python_version='2.7')"
    working_directory: /usr/src/artman/

  unit-python3.4:
    docker:
      - image: python:3.4
    steps:
      - *checkout_artman
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox-automation codecov
      - run:
          name: Run unit tests.
          command: nox -e "unit_tests(python_version='3.4')"
    working_directory: /usr/src/artman/

  unit-python3.5:
    docker:
      - image: python:3.5
    steps:
      - *checkout_artman
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox-automation codecov
      - run:
          name: Run unit tests.
          command: nox -e "unit_tests(python_version='3.5')"
    working_directory: /usr/src/artman/

  unit-python3.6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox-automation codecov
      - run:
          name: Run unit tests.
          command: nox -e "unit_tests(python_version='3.6')"
    working_directory: /usr/src/artman/

  smoke-csharp:
    docker:
      - image: googleapis/artman:latest
        environment:
          TERM: dumb
    steps:
      - *checkout_artman
      - run:
          name: Install latest artman
          command: |
            pip uninstall -y googleapis-artman
            pip install --upgrade -e /usr/src/artman/
      - run:
          name: Build Pub/Sub (C#)
          command: artman --local --config=google/pubsub/artman_pubsub.yaml --root-dir=/googleapis generate csharp_gapic
      - run:
          name: Build Speech (C#)
          command: artman --local --config=google/cloud/speech/artman_speech_v1.yaml --root-dir=/googleapis generate csharp_gapic
    working_directory: /usr/src/artman/  # Intended, in order to test --root-dir flag.

  smoke-go:
    docker:
      - image: googleapis/artman:latest
        environment:
          TERM: dumb
    steps:
      - *checkout_artman
      - run:
          name: Install latest artman
          command: |
            pip uninstall -y googleapis-artman
            pip install --upgrade -e /usr/src/artman/
      - run:
          name: Build Pub/Sub (Go)
          command: |
            mkdir /tmp/pubsub-go
            artman --local --output-dir /tmp/pubsub-go --config=google/pubsub/artman_pubsub.yaml publish --dry-run --github-username foo --github-token bar --target staging go_gapic
      - run:
          name: Build Speech (Go)
          command: |
            mkdir /tmp/speech-go
            artman --local --output-dir /tmp/speech-go --config=google/cloud/speech/artman_speech_v1.yaml publish --dry-run --github-username foo --github-token bar --target staging go_gapic
    working_directory: /googleapis

  smoke-java:
    docker:
      - image: googleapis/artman:latest
        environment:
          TERM: dumb
    steps:
      - *checkout_artman
      - run:
          name: Install latest artman
          command: |
            pip uninstall -y googleapis-artman
            pip install --upgrade -e /usr/src/artman/
      - run:
          name: Build Pub/Sub (Java)
          command: |
            git clone https://github.com/googleapis/api-client-staging /tmp/api-client-staging
            artman --local --config=google/pubsub/artman_pubsub.yaml publish --dry-run --local-repo-dir=/tmp/api-client-staging --github-username foo --github-token bar --target staging java_gapic
      - run:
          name: Build Speech (Java)
          command: |
            mkdir /tmp/speech-java
            artman --local --output-dir /tmp/speech-java --config=google/cloud/speech/artman_speech_v1.yaml publish --dry-run --github-username foo --github-token bar --target staging java_gapic
    working_directory: /googleapis

  smoke-nodejs:
    docker:
      - image: googleapis/artman:latest
        environment:
          TERM: dumb
    steps:
      - *checkout_artman
      - run:
          name: Install latest artman
          command: |
            pip uninstall -y googleapis-artman
            pip install --upgrade -e /usr/src/artman/
      - run:
          name: Build Pub/Sub (Node.js)
          command: |
            mkdir /tmp/pubsub-node
            artman --local --output-dir /tmp/pubsub-node --config=google/pubsub/artman_pubsub.yaml publish --dry-run --github-username foo --github-token bar --target staging nodejs_gapic
      - run:
          name: Build Speech (Node.js)
          command: |
            mkdir /tmp/speech-node
            artman --local --output-dir speech-node --config=google/cloud/speech/artman_speech_v1.yaml publish --dry-run --github-username foo --github-token bar --target staging nodejs_gapic
    working_directory: /googleapis

  smoke-php:
    docker:
      - image: googleapis/artman:latest
        environment:
          TERM: dumb
    steps:
      - *checkout_artman
      - run:
          name: Install latest artman
          command: |
            pip uninstall -y googleapis-artman
            pip install --upgrade -e /usr/src/artman/
      - run:
          name: Build Pub/Sub (PHP)
          command: |
            mkdir /tmp/pubsub-php
            artman --local --output-dir /tmp/pubsub-php --config=google/pubsub/artman_pubsub.yaml publish --dry-run --github-username foo --github-token bar --target staging php_gapic
      - run:
          name: Build Speech (PHP)
          command: |
            mkdir /tmp/speech-php
            artman --local --output-dir /tmp/speech-php --config=google/cloud/speech/artman_speech_v1.yaml publish --dry-run --github-username foo --github-token bar --target staging php_gapic
    working_directory: /googleapis

  smoke-python:
    docker:
      - image: googleapis/artman:latest
        environment:
          TERM: dumb
    steps:
      - *checkout_artman
      - run:
          name: Install latest artman
          command: |
            pip uninstall -y googleapis-artman
            pip install --upgrade -e /usr/src/artman/
      - run:
          name: Build Pub/Sub (Python)
          command: |
            mkdir /tmp/pubsub-python
            artman --local --output-dir /tmp/pubsub-python --config=google/pubsub/artman_pubsub.yaml publish --dry-run --github-username foo --github-token bar --target staging python_gapic
      - run:
          name: Build Speech (Python)
          command: |
            mkdir /tmp/speech-python
            artman --local --output-dir /tmp/speech-python --config=google/cloud/speech/artman_speech_v1.yaml publish --dry-run --github-username foo --github-token bar --target staging python_gapic
    working_directory: /googleapis

  smoke-ruby:
    docker:
      - image: googleapis/artman:latest
        environment:
          TERM: dumb
    steps:
      - *checkout_artman
      - run:
          name: Install latest artman
          command: |
            pip uninstall -y googleapis-artman
            pip install --upgrade -e /usr/src/artman/
      - run:
          name: Build Pub/Sub (Ruby)
          command: |
            mkdir /tmp/pubsub-ruby
            artman --local --output-dir /tmp/pubsub-ruby --config=google/pubsub/artman_pubsub.yaml publish --dry-run --github-username foo --github-token bar --target staging ruby_gapic
      - run:
          name: Build Speech (Ruby)
          command: |
            mkdir /tmp/speech-ruby
            artman --local --output-dir /tmp/speech-ruby --config=google/cloud/speech/artman_speech_v1.yaml publish --dry-run --github-username foo --github-token bar --target staging ruby_gapic
    working_directory: /googleapis

workflows:
  version: 2
  tests:
    jobs:
      - unit-python2.7
      - unit-python3.4
      - unit-python3.5
      - unit-python3.6
      - docs
      - smoke-csharp
      - smoke-go
      - smoke-java
      - smoke-nodejs
      - smoke-php
      - smoke-python
      - smoke-ruby
  build_and_push_docker_image:
    jobs:
      - build_and_push_docker_image:
          filters:
            branches:
              only: master
